export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const MIS_UPLOAD_SHEET_SUCCESS = 'MIS_UPLOAD_SHEET_SUCCESS'
export const MIS_UPLOAD_SHEET_FAIL = 'MIS_UPLOAD_SHEET_FAIL'

export const MIS_GET_ERROR = "MIS_GET_ERROR"
export const MIS_GET_SUCCESS = "MIS_GET_SUCCESS"

export const MIS_ERROR_GET_SUCCESS = "MIS_ERROR_GET_SUCCESS"
export const MIS_ERROR_GET_ERROR = "MIS_ERROR_GET_ERROR"
