export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const MIS_UPLOAD_SHEET_SUCCESS = 'MIS_UPLOAD_SHEET_SUCCESS'
export const MIS_UPLOAD_SHEET_FAIL = 'MIS_UPLOAD_SHEET_FAIL'

export const MIS_GET_ERROR = "MIS_GET_ERROR"
export const MIS_GET_SUCCESS = "MIS_GET_SUCCESS"

export const MIS_ERROR_GET_SUCCESS = "MIS_ERROR_GET_SUCCESS"
export const MIS_ERROR_GET_ERROR = "MIS_ERROR_GET_ERROR"

export const GET_GRAPH_COUNT_BY_CENTER_TYPE_SUCCESS = "GET_GRAPH_COUNT_BY_CENTER_TYPE_SUCCESS"
export const GET_GRAPH_COUNT_BY_CENTER_TYPE_ERROR = "GET_GRAPH_COUNT_BY_CENTER_TYPE_ERROR"

export const GET_GRAPH_COUNT_BY_INSTALLATION_SUCCESS = "GET_GRAPH_COUNT_BY_INSTALLATION_SUCCESS"
export const GET_GRAPH_COUNT_BY_INSTALLATION_ERROR = "GET_GRAPH_COUNT_BY_INSTALLATION_ERROR"

export const GET_GRAPH_COUNT_BY_QC_SUCCESS = "GET_GRAPH_COUNT_BY_QC_SUCCESS"
export const GET_GRAPH_COUNT_BY_QC_ERROR = "GET_GRAPH_COUNT_BY_QC_ERROR"

export const GET_GRAPH_COUNT_BY_MOCK_SUCCESS = "GET_GRAPH_COUNT_BY_MOCK_SUCCESS"
export const GET_GRAPH_COUNT_BY_MOCK_ERROR = "GET_GRAPH_COUNT_BY_MOCK_ERROR"

export const GET_PROJECT_DETAILS_SUCCESS = "GET_PROJECT_DETAILS_SUCCESS"
export const GET_PROJECT_DETAILS_ERROR = "GET_PROJECT_DETAILS_ERROR"

export const GET_ZM_SUCCESS = "GET_ZM_SUCCESS"
export const GET_ZM_ERROR = "GET_ZM_ERROR"

export const GET_PM_SUCCESS = "GET_PM_SUCCESS"
export const GET_PM_ERROR = "GET_PM_ERROR"